-- AlterTable
ALTER TABLE "account" ADD COLUMN     "dana_given" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "dana_received" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN     "total_dana" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
