/* eslint-disable */ /**
  *
  * THIS FILE IS AUTOGENERATED, DO NOT EDIT IT!
  *
  * instead, edit one of the `.graphql` files in this project and run
  *
  * yarn graphql-codegen
  *
  * for this file to be re-created
  */

import * as Types from '../../generated/types.generated';

import { PostInfoFieldsFragmentDoc } from '../../graphql/fragments/post-info-fields.fragment.generated';
import { api } from 'src/api/baseApi';
export type PostQueryVariables = Types.Exact<{
  id: Types.Scalars['String'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename?: 'Post', id: string, title: string, content: string, cover?: string | null, createdAt: any, updatedAt: any } };

export type PostsQueryVariables = Types.Exact<{
  after?: Types.InputMaybe<Types.Scalars['String']>;
  before?: Types.InputMaybe<Types.Scalars['String']>;
  first?: Types.InputMaybe<Types.Scalars['Int']>;
  last?: Types.InputMaybe<Types.Scalars['Int']>;
  orderBy?: Types.InputMaybe<Types.PostOrder>;
  query?: Types.InputMaybe<Types.Scalars['String']>;
  skip?: Types.InputMaybe<Types.Scalars['Int']>;
}>;


export type PostsQuery = { __typename?: 'Query', allPosts: { __typename?: 'PostConnection', totalCount?: number | null, edges?: Array<{ __typename?: 'PostEdge', cursor: string, node: { __typename?: 'Post', id: string, title: string, content: string, cover?: string | null, createdAt: any, updatedAt: any } }> | null, postInfo: { __typename?: 'PostInfo', endCursor?: string | null, hasNextPage: boolean, hasPreviousPage: boolean, startCursor?: string | null } } };

export type PostFieldsFragment = { __typename?: 'Post', id: string, title: string, content: string, cover?: string | null, createdAt: any, updatedAt: any };

export type CreatePostMutationVariables = Types.Exact<{
  input: Types.CreatePostInput;
}>;


export type CreatePostMutation = { __typename?: 'Mutation', createPost: { __typename?: 'Post', id: string, title: string, content: string, cover?: string | null, createdAt: any, updatedAt: any } };

export type UpdatePostMutationVariables = Types.Exact<{
  input: Types.UpdatePostInput;
}>;


export type UpdatePostMutation = { __typename?: 'Mutation', updatePost: { __typename?: 'Post', id: string, title: string, content: string, cover?: string | null, createdAt: any, updatedAt: any } };

export const PostFieldsFragmentDoc = `
    fragment PostFields on Post {
  id
  title
  content
  cover
  createdAt
  updatedAt
}
    `;
export const PostDocument = `
    query Post($id: String!) {
  post(id: $id) {
    ...PostFields
  }
}
    ${PostFieldsFragmentDoc}`;
export const PostsDocument = `
    query Posts($after: String, $before: String, $first: Int = 20, $last: Int = 20, $orderBy: PostOrder, $query: String, $skip: Int) {
  allPosts(
    after: $after
    before: $before
    first: $first
    last: $last
    orderBy: $orderBy
    query: $query
    skip: $skip
  ) {
    totalCount
    edges {
      cursor
      node {
        ...PostFields
      }
    }
    postInfo {
      ...PostInfoFields
    }
  }
}
    ${PostFieldsFragmentDoc}
${PostInfoFieldsFragmentDoc}`;
export const CreatePostDocument = `
    mutation createPost($input: CreatePostInput!) {
  createPost(data: $input) {
    ...PostFields
  }
}
    ${PostFieldsFragmentDoc}`;
export const UpdatePostDocument = `
    mutation updatePost($input: UpdatePostInput!) {
  updatePost(data: $input) {
    ...PostFields
  }
}
    ${PostFieldsFragmentDoc}`;

const injectedRtkApi = api.injectEndpoints({
  endpoints: (build) => ({
    Post: build.query<PostQuery, PostQueryVariables>({
      query: (variables) => ({ document: PostDocument, variables })
    }),
    Posts: build.query<PostsQuery, PostsQueryVariables | void>({
      query: (variables) => ({ document: PostsDocument, variables })
    }),
    createPost: build.mutation<CreatePostMutation, CreatePostMutationVariables>({
      query: (variables) => ({ document: CreatePostDocument, variables })
    }),
    updatePost: build.mutation<UpdatePostMutation, UpdatePostMutationVariables>({
      query: (variables) => ({ document: UpdatePostDocument, variables })
    }),
  }),
});

export { injectedRtkApi as api };
export const { usePostQuery, useLazyPostQuery, usePostsQuery, useLazyPostsQuery, useCreatePostMutation, useUpdatePostMutation } = injectedRtkApi;

