export const NOTIFICATION_TYPES = {
  // LIXI
  CREATE_SUB_LIXIES: 1,
  WITHDRAW_SUB_LIXIES: 2,
  EXPORT_SUB_LIXIES: 3,
  CREATE_SUB_LIXIES_FAILURE: 4,
  // LixiLotus
  POST_ON_PAGE: 5,
  COMMENT_ON_POST: 6,
  COMMENT_TO_GIVE: 7,
  BURN: 8,
  RECEIVE_BURN_TIP: 9,
  RECEIVE_BURN_FEE: 10,
  // GET XPI:
  GET_XPI: 11,
  FOLLOW_ACCOUNT: 12,
  FOLLOW_PAGE: 13
};

export const NOTIFICATION_OUTBOUND_QUEUE = 'NOTIFICATION_OUTBOUND_QUEUE';
