export const NOTIFICATION_TYPES = {
  // LIXI
  CREATE_SUB_LIXIES: 1,
  WITHDRAW_SUB_LIXIES: 2,
  EXPORT_SUB_LIXIES: 3,
  CREATE_SUB_LIXIES_FAILURE: 4,
  // Lixi
  POST_ON_PAGE: 5,
  COMMENT_ON_POST: 6,
  COMMENT_TO_GIVE: 7,
  RECEIVE_BURN_COMMENT_ACCOUNT: 8,
  RECEIVE_BURN_ACCOUNT: 9,
  RECEIVE_BURN_PAGE: 10,
  // GET XPI:
  GET_XPI: 11,
  FOLLOW_ACCOUNT: 12,
  FOLLOW_PAGE: 13,
  NEW_POST: 14
};

export const WEBPUSH_CLIENT_APP_IDS = {
  LIXI_LOTUS: 'lixilotus',
  LOTUS_TEMPLE: 'lotustemple'
};

export const NOTIFICATION_OUTBOUND_QUEUE = 'NOTIFICATION_OUTBOUND_QUEUE';
export const WEBPUSH_NOTIFICATION_QUEUE = 'WEBPUSH_NOTIFICATION_QUEUE';
