export const defaultLixiChunkSize = 2000;
export const CREATE_SUB_LIXIES_QUEUE = 'CREATE_SUB_LIXIES_QUEUE';
export const EXPORT_SUB_LIXIES_QUEUE = 'EXPORT_SUB_LIXIES_QUEUE';
export const WITHDRAW_SUB_LIXIES_QUEUE = 'WITHDRAW_SUB_LIXIES_QUEUE';

export const LIXI_JOB_NAMES = {
  CREATE_SUB_LIXIES_CHUNK: 'CREATE_SUB_LIXIES_CHUNK',
  CREATE_ALL_SUB_LIXIES: 'CREATE_ALL_SUB_LIXIES',
  WITHDRAW_ALL_SUB_LIXIES: 'WITHDRAW_ALL_SUB_LIXIES',
  EXPORT_ALL_SUB_LIXIES: 'EXPORT_ALL_SUB_LIXIES'
}
